# Import all the libraries here

In [3]:
# basic
import numpy as np
import pandas as pd

# plotting
import seaborn as sns
import matplotlib.pyplot as plt

# ml preprocessing
from sklearn.model_selection import train_test_split

# ml models
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

# ml metrics
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error, mean_squared_error

# additional settings
import warnings
pd.set_option('display.max_columns', None)
warnings.filterwarnings("ignore")

## Load data

In [4]:
data = pd.read_csv("../data/financial_data_ml.csv", index_col=0)
df = data.copy()

In [5]:
df.head(4)

,date,inflation,unemployment,gdp,fed_int_rate,ten_year_yield,m2_money_supp,consum_sent_idx,indus_pro_idx,exports,imports,new_home_const,mortgage_rate,vix,wti,volume,month,year,inflation_pct_change,gdp_pct_change,m2_money_supp_pct_change,exports_pct_change,imports_pct_change,new_home_const_pct_change,wti_pct_change,inflation_category,interest_rate_category,crisis_period,sp_close_pct_change,sp_close
0,2000-04-01,170.9,3.8,10247.72,6.02,6.03,4767.8,109.2,92.6659,1093.36,1455.86,1626.0,8.23,24.11,26.86,1.227400e+09,Apr,2000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,Low,Hawkish,Stable,0.000000,1498.579956
1,2000-04-03,170.9,3.8,10247.72,6.02,6.00,4767.8,109.2,92.6659,1093.36,1455.86,1626.0,8.23,24.03,26.28,1.021700e+09,Apr,2000,0.0,0.0,0.0,0.0,0.0,0.0,-2.159345,Low,Hawkish,Stable,0.493134,1505.969971
2,2000-04-04,170.9,3.8,10247.72,6.02,5.90,4767.8,109.2,92.6659,1093.36,1455.86,1626.0,8.23,27.12,25.46,1.515460e+09,Apr,2000,0.0,0.0,0.0,0.0,0.0,0.0,-3.120244,Low,Hawkish,Stable,-0.746362,1494.729980
3,2000-04-05,170.9,3.8,10247.72,6.02,5.90,4767.8,109.2,92.6659,1093.36,1455.86,1626.0,8.23,28.41,25.76,1.110300e+09,Apr,2000,0.0,0.0,0.0,0.0,0.0,0.0,1.178319,Low,Hawkish,Stable,-0.492396,1487.369995

In [6]:
df["crisis_period"].value_counts()

crisis_period
Stable                   4489
Financial Crisis          793
Russia-Ukraine crisis     792
COVID-19                  529
Name: count, dtype: int64